/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContactResponseAddress } from './contactResponseAddress';
import { ContactResponseCompany } from './contactResponseCompany';
import { ContactResponseNote } from './contactResponseNote';

export class AccountResponseContact {
    /**
    * Email address
    */
    'email': string | null;
    /**
    * Phone number
    */
    'phoneNumber': string | null;
    /**
    * Mobile number
    */
    'mobileNumber': string;
    /**
    * Fax number
    */
    'faxNumber': string | null;
    /**
    * Time of creation
    */
    'createdAt': Date;
    /**
    * Contact Id
    */
    'contactId': string;
    /**
    * First name
    */
    'firstName': string;
    /**
    * Middle initial
    */
    'middleInitial'?: string;
    /**
    * Last name
    */
    'lastName': string;
    /**
    * A list of companies that contact belongs to
    */
    'companies': Array<ContactResponseCompany>;
    /**
    * Notes about the contact
    */
    'notes': Array<ContactResponseNote>;
    'address': ContactResponseAddress | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "faxNumber",
            "baseName": "faxNumber",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "contactId",
            "baseName": "contactId",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "middleInitial",
            "baseName": "middleInitial",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "companies",
            "baseName": "companies",
            "type": "Array<ContactResponseCompany>"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<ContactResponseNote>"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "ContactResponseAddress"
        }    ];

    static getAttributeTypeMap() {
        return AccountResponseContact.attributeTypeMap;
    }
}

