/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContactResponseAddress } from './contactResponseAddress';

export class CompanyContactResponse {
    /**
    * Email address
    */
    'email': string | null;
    /**
    * Phone number
    */
    'phoneNumber': string | null;
    /**
    * Mobile number
    */
    'mobileNumber': string;
    /**
    * Fax number
    */
    'faxNumber': string | null;
    /**
    * Time of creation
    */
    'createdAt': Date;
    /**
    * Contact Id
    */
    'contactId': string;
    /**
    * First name
    */
    'firstName': string;
    /**
    * Middle name
    */
    'middleInitial'?: string;
    /**
    * Last name
    */
    'lastName': string;
    'address': ContactResponseAddress | null;
    /**
    * Account Id
    */
    'accountId': string;
    /**
    * Payment provider Id
    */
    'paymentProviderId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "faxNumber",
            "baseName": "faxNumber",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "contactId",
            "baseName": "contactId",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "middleInitial",
            "baseName": "middleInitial",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "ContactResponseAddress"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "paymentProviderId",
            "baseName": "paymentProviderId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CompanyContactResponse.attributeTypeMap;
    }
}

