/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ContactResponseNote {
    /**
    * The note about the contact.
    */
    'text': string;
    /**
    * The timestamp when the note was created
    */
    'createdAt': string;
    /**
    * UUID of the user who created the note
    */
    'createdBy': string;
    /**
    * The full name of the person who created the note
    */
    'createdByFullName': string;
    /**
    * The timestamp when the note was last updated
    */
    'updatedAt': string;
    /**
    * UUID of the user who last updated the note
    */
    'updatedBy': string;
    /**
    * Contact Note Id
    */
    'contactNoteId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "createdByFullName",
            "baseName": "createdByFullName",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string"
        },
        {
            "name": "contactNoteId",
            "baseName": "contactNoteId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ContactResponseNote.attributeTypeMap;
    }
}

