/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContactRequest } from './contactRequest';

export class CreateContactsRequest {
    /**
    * Contacts
    */
    'contacts': Array<ContactRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contacts",
            "baseName": "contacts",
            "type": "Array<ContactRequest>"
        }    ];

    static getAttributeTypeMap() {
        return CreateContactsRequest.attributeTypeMap;
    }
}

