/**
 * ManageSpace CRM API
 * ManageSpace CRM API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContactAddressRequest } from './contactAddressRequest';

export class UpdateContactRequest {
    /**
    * Email address
    */
    'email'?: string;
    /**
    * Phone number
    */
    'phoneNumber'?: string;
    /**
    * Mobile number
    */
    'mobileNumber': string;
    /**
    * Fax number
    */
    'faxNumber'?: string;
    /**
    * First name
    */
    'firstName': string;
    /**
    * Middle name
    */
    'middleInitial'?: string;
    /**
    * Last name
    */
    'lastName': string;
    'address'?: ContactAddressRequest;
    /**
    * Contact ID
    */
    'contactId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "faxNumber",
            "baseName": "faxNumber",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "middleInitial",
            "baseName": "middleInitial",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "ContactAddressRequest"
        },
        {
            "name": "contactId",
            "baseName": "contactId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateContactRequest.attributeTypeMap;
    }
}

